### ISSUE TITLE
Encryption via Cryptofs

### ISSUE THREAD

**Issue by Bios-Marcel** [Bios-Marcel/baka#1]
https://github.com/cryptomator/cryptofs

**Comment by MarvinKlar** [comment]
CryptoFS relies on jdk.crypto.ec, which is being removed soon, BUT https://bugs.openjdk.org/browse/JDK-8312267

We can potentially just patch this.

**Comment by Bios-Marcel** [comment]
Note to self:

The MVP we wrote over at https://github.com/MarvinKlar/baka/tree/wip_cryptofs works

We need to polish the UI and UX a bit though.

The riddle as to why multi channel didn't work with cryptofs, is that we didn't shutdown the storage manager on application exit.

Optional encryption would probably be good. We could have two different directories, depending on which is present we allow the user to chose. The only reason why cryptofs might not be a good choice for everyone, is the performance. Even small amounts of data seem to load slower. We should do benchmarking here.

**Comment by Bios-Marcel** [comment]
FYI, I found out cryptofs can lead to corrupted data on crashes. Therefore no cryptofs for now, can't be arsed :D
